# Generated by Django 6.0.3 on 2026-06-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_directmessage_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='audio',
            field=models.FileField(blank=True, help_text='Note vocale.', null=True, upload_to='community/support/audio/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='audio_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, help_text='Note vocale.', null=True, upload_to='community/audio/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_duration',
            field=models.PositiveIntegerField(default=0, help_text='Durée de la note vocale (s).'),
        ),
    ]
