# Generated by Django 6.0.3 on 2026-06-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_adress_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='code_postal',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='adress',
            name='country',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='adress',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
