# Generated by Django 6.0.3 on 2026-06-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_fcm_token_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='read_receipts',
            field=models.BooleanField(default=True, help_text="Si désactivé, l'utilisateur n'envoie plus d'accusés de lecture (personne ne voit quand il a lu un message)."),
        ),
    ]
