# Generated by Django 6.0.3 on 2026-06-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_rebrand_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='apk_url',
            field=models.URLField(blank=True, help_text="Lien direct vers l'APK hébergé ailleurs (ex : GitHub Release). Recommandé pour les gros fichiers : si renseigné, il est utilisé en priorité et aucun upload n'est nécessaire.", max_length=500, null=True),
        ),
    ]
